import React, { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
import "./content.css";

const projects=[
 {no:"01",title:"AI Job Recommendation System",type:"Published research · NLP",text:"A BERT-powered recommendation engine that extracts skills from job descriptions and candidate profiles, then uses Artificial Bee Colony optimisation to rank role relevance.",stack:["Python","BERT","NLP","ABC"],stat:"Published in Springer · ICONWIL 2024",tone:"violet",image:"jpeg/job.jpeg"},
 {no:"02",title:"Promise Tracker",type:"Productivity system",text:"A focused promise-tracking experience that makes commitments, ownership, deadlines and follow-through visible instead of forgotten.",stack:["React","JavaScript","UX"],stat:"Independent build · actively evolving",tone:"cyan",image:"jpeg/promise-tracker-v2.png"},
 {no:"03",title:"Perishable Food Management",type:"SaaS inventory system",text:"A Python and MongoDB application for managing perishable inventory with batch visibility, smart reminders and practical incoming/outgoing workflows.",stack:["Python","MongoDB","PyMongo"],stat:"Inventory + operations",tone:"blue",image:"jpeg/food.jpeg"},
 {no:"04",title:"Water Quality Analysis",type:"Machine learning",text:"A classification project that evaluates water quality using features including conductivity, hardness and pH to support faster, more informed decisions.",stack:["Python","ML","Analytics"],stat:"Decision Tree + Logistic Regression",tone:"violet",image:"jpeg/water.jpeg"},
 {no:"05",title:"Road Safety IoT System",type:"Connected systems",text:"An all-in-one Arduino Mega 2560 device that tracks lane traffic, vehicle speed, air quality and automatic streetlight behaviour through sensor data.",stack:["Arduino","IoT","Sensors"],stat:"Real-world monitoring",tone:"cyan",image:"jpeg/road.jpeg"},
 {no:"06",title:"Airline Reservation",type:"Full-stack web app",text:"A booking experience that pairs a clear customer interface with PHP and MySQL-backed ticket reservation and availability workflows.",stack:["PHP","MySQL","HTML/CSS"],stat:"End-to-end reservation flow",tone:"blue",image:"jpeg/airlines.jpeg"}
];
const skills=[["Frontend","React · JavaScript · CSS","◩"],["Backend","Python · C# · .NET · Node","◇"],["Data","SQL · MySQL · MongoDB","◌"],["AI systems","LLMs · RAG · Agents · NLP","✦"],["Cloud & tools","Git · CI/CD · Linux · Docker","◫"],["Thinking","DSA · OOP · Analytics","↯"]];
function App(){
 const[menu,setMenu]=useState(false),[ready,setReady]=useState(false),[scroll,setScroll]=useState(0),[contactStatus,setContactStatus]=useState("idle");
 useEffect(()=>{const t=setTimeout(()=>setReady(true),850);const update=()=>setScroll(scrollY/Math.max(1,document.body.scrollHeight-innerHeight));const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setMenu(true)}if(e.key==="Escape")setMenu(false)};addEventListener("scroll",update,{passive:true});addEventListener("keydown",key);return()=>{clearTimeout(t);removeEventListener("scroll",update);removeEventListener("keydown",key)}},[]);
 const jump=id=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:"smooth"})};
 const submitContact=async event=>{event.preventDefault();const form=event.currentTarget;setContactStatus("sending");try{const response=await fetch("https://formsubmit.co/ajax/puneethraj677@gmail.com",{method:"POST",body:new FormData(form),headers:{Accept:"application/json"}});if(!response.ok)throw new Error("delivery failed");form.reset();setContactStatus("sent")}catch{setContactStatus("error")}};
 return <><div className={`loader ${ready?"done":""}`}><strong>PR</strong><i/><small>INITIALIZING / 2026</small></div><div className="progress" style={{transform:`scaleX(${scroll})`}}/>
 <header className="nav"><button className="brand" onClick={()=>jump("top")}>P<span>R</span></button><nav><button onClick={()=>jump("work")}>Work</button><button onClick={()=>jump("about")}>About</button><button onClick={()=>jump("contact")}>Contact</button></nav><button className="menu-button" onClick={()=>setMenu(true)} aria-label="Open navigation menu"><span>⌘</span> MENU</button></header>
 {menu&&<div className="palette" onClick={()=>setMenu(false)} role="dialog" aria-modal="true"><div className="palette-card" onClick={e=>e.stopPropagation()}><div className="palette-title">Navigate Puneeth&apos;s universe <kbd>ESC</kbd></div>{[["01","Selected work","work"],["02","About","about"],["03","Playground","playground"],["04","Contact","contact"]].map(([no,label,id])=><button key={id} onClick={()=>jump(id)}><small>{no}</small>{label}<b>↗</b></button>)}</div></div>}
 <main><section className="hero" id="top"><div className="orb orb-left"/><div className="orb orb-right"/><div className="grain"/><div className="hero-copy"><p className="eyebrow"><i/> AVAILABLE FOR SELECTED COLLABORATIONS</p><h1>I build digital<br/><em>experiences</em> that<br/>feel alive<span>.</span></h1><p className="lede">I&apos;m Puneeth Raj - a software developer who likes building useful things, learning how systems work, and turning ideas into experiences people can actually rely on.</p><div className="actions"><button className="button-primary" onClick={()=>jump("work")}>View projects <b>↓</b></button><button className="button-text" onClick={()=>jump("contact")}>Let&apos;s talk <b>↗</b></button></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="core">&lt;/&gt;</div><div className="code-card"><small>intention.js</small><code><b>const</b> build =<br/>&nbsp; <i>(idea) =&gt;</i> alive;</code></div><div className="status-card"><i/> SYSTEMS / ONLINE<span>crafting the next thing</span></div><div className="coordinates">12°58&apos; N&nbsp;&nbsp;77°35&apos; E<br/><b>BENGALURU / INDIA</b></div></div><p className="scroll-note">SCROLL TO EXPLORE <b>↓</b></p></section><div className="marquee" aria-label="Full-stack, AI-native, human-centered, systems thinker"><div className="marquee-track"><span>FULL-STACK <i>✦</i> AI-NATIVE <i>✦</i> HUMAN-CENTERED <i>✦</i> SYSTEMS THINKER <i>✦</i></span><span aria-hidden="true">FULL-STACK <i>✦</i> AI-NATIVE <i>✦</i> HUMAN-CENTERED <i>✦</i> SYSTEMS THINKER <i>✦</i></span></div></div>
 <section className="section about" id="about"><p className="label">01 / ABOUT THE BUILDER</p><div className="about-grid"><div><h2>Every great product<br/>starts with a <em>good question.</em></h2><p>I&apos;m a software developer who enjoys turning messy, high-stakes workflows into dependable systems. My work moves between enterprise automation, data-heavy financial platforms, full-stack applications and AI-native tools - always with an eye on the person who has to use it next.</p><a className="resume-link" href="https://drive.google.com/file/d/1gRqBOs7LnAmx1Ifs6LpfFCMGt9JKPl8w/view?usp=sharing" target="_blank" rel="noreferrer">Read my full résumé <b>↗</b></a></div><div className="constellation">{["React","JavaScript","Python","C#",".NET","SQL","MySQL","MongoDB","Node.js","LLMs","RAG","AI Agents","Prompting","NLP","BERT","REST APIs","Git","CI/CD","Docker","Linux","Power BI","Excel","IoT","DSA"].map((s,i)=><span key={s} className={`star star-${i}`}>{s}</span>)}</div></div></section>
 <section className="section skill-section"><p className="label">02 / SKILL CONSTELLATION</p><div className="heading-row"><h2>A toolkit for<br/><em>making it real.</em></h2><p>Tools are temporary. Curiosity, taste, and a bias for shipping are the durable parts.</p></div><div className="skills">{skills.map(([title,copy,mark],i)=><article className="skill" key={title}><small>0{i+1}</small><strong>{mark}</strong><h3>{title}</h3><p>{copy}</p><b>↗</b></article>)}</div></section>
 <section className="section work" id="work"><p className="label">03 / SELECTED SIGNALS</p><h2>Things I&apos;ve made<br/><em>with intent.</em></h2><div className="project-list">{projects.map(p=><article className="project" key={p.no}><div className={`project-art ${p.tone}`}>{p.image&&<img src={`${import.meta.env.BASE_URL}assets/${p.image}`} alt={`${p.title} project preview`}/>}<small>{p.no}</small><span>{p.type}</span></div><div className="project-copy"><div><p>{p.type}</p><h3>{p.title}</h3><article>{p.text}</article></div><footer><div>{p.stack.map(x=><span key={x}>{x}</span>)}</div><small>{p.stat}</small></footer></div><a href="#contact" aria-label={`Ask about ${p.title}`}>↗</a></article>)}</div></section>
 <section className="section playground" id="playground"><p className="label">04 / DEVELOPER PLAYGROUND</p><div className="play-grid"><div><h2>Somewhere between<br/>logic and <em>magic.</em></h2><p>A living notebook for ideas that refuse to stay theoretical.</p><div className="heatmap">{Array.from({length:84},(_,i)=><i key={i} className={`heat-${(i*7)%5}`}/>)}</div><small>CONTRIBUTION ENERGY / ALWAYS IN BETA</small></div><div className="terminal"><header><i/><i/><i/><span>puneeth@studio:~</span></header><pre><span>$</span> npm run curiosity{"\n"}<b>✓</b> Compiling a better question...{"\n"}<span>→</span> Designing systems that care.{"\n\n"}<i>const</i> possibility = await imagination(){"\n"}<span>✓</span> shipped: something useful</pre><b className="cursor"/></div></div></section>
 <section className="section timeline"><p className="label">05 / THE PATH SO FAR</p><h2>Learning in public.<br/><em>Building in earnest.</em></h2><div>{[["2024 — now","Software Developer","Winman Software India LLP","Builds and improves automation tools within the Winman CAERP platform for financial workflows. Developed an ITR discrepancy-detection module using validation and anomaly detection that reduced verification time by about 70%. Also contributes to LLM agents, reusable AI skills, prompt-engineering workflows, production issue resolution, performance optimisation, and stronger delivery practices across planning, reviews, testing and releases."],["2022","Python Developer Intern","Duroflex Private Limited","Optimised SQL-to-Excel reporting workflows with Python multithreading, improving data-export speed and operational efficiency. Partnered with the internal IT team to troubleshoot bugs, make scripts more reliable, and streamline recurring reporting automation."],["2020 — 2024","B.Tech, Computer Science","PES University, Bengaluru","Studied software engineering, data structures, object-oriented programming, machine learning and NLP. Built research-led and practical projects spanning job recommendations, IoT, data analytics and full-stack web systems."]].map(([year,role,company,copy])=><article key={year}><div><small>{year}</small><b>{role}</b></div><p>{company}</p><span>{copy}</span></article>)}</div></section><section className="achievement"><div><p>RESEARCH / RECOGNITION</p><h2>Built a recommendation engine.<br/><em>Then took it to Springer.</em></h2><span>ICONWIL 2024</span><span>Published research</span><span>NLP + Optimization</span><a className="research-link" href="https://link.springer.com/chapter/10.1007/978-981-96-0201-8_57" target="_blank" rel="noreferrer">Read the Springer publication ↗</a></div></section></main>
 <footer className="contact" id="contact"><div className="contact-glow"/><p className="eyebrow"><i/> OPEN TO THOUGHTFUL WORK</p><h2>Let&apos;s build something<br/><em>impossible.</em></h2><a className="email" href="mailto:puneethraj677@gmail.com">puneethraj677@gmail.com <b>↗</b></a><form onSubmit={submitContact}><input type="hidden" name="_subject" value="New portfolio message for Puneeth Raj"/><input type="hidden" name="_template" value="table"/><input type="text" name="_honey" className="hidden-field" tabIndex="-1" autoComplete="off"/><label>Name<input required name="name" placeholder="What should I call you?"/></label><label>Email<input required name="email" type="email" placeholder="Where can I reach you?"/></label><label className="message">The idea<textarea required name="message" placeholder="Tell me what we could make together..."/></label><button className="button-primary" disabled={contactStatus==="sending"}>{contactStatus==="sending"?"Sending...":contactStatus==="sent"?"Message sent ✓":"Send the signal ↗"}</button></form>{contactStatus==="sent"&&<small className="contact-note success">Thanks - your message has been sent.</small>}{contactStatus==="error"&&<small className="contact-note error">Something went wrong. Please email me directly instead.</small>}<div className="contact-bottom"><p>Bengaluru, India<br/>Available worldwide</p><nav><a href="https://www.linkedin.com/in/s-puneeth-raj-9bb329234/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://github.com/puneeee" target="_blank" rel="noreferrer">GitHub ↗</a><button onClick={()=>jump("top")}>Back to top ↑</button></nav><p>© 2026 PUNEETH RAJ<br/>BUILT WITH INTENTION</p></div></footer></>}
createRoot(document.getElementById("root")).render(<StrictMode><App/></StrictMode>);
